# Configuration optimized for tracking shots (following subjects)

pipeline:
  use_cache: true
  detect_shots: true
  motion_analysis: true

frame_extraction:
  fps: 5.0  # Higher FPS for tracking shots

scoring:
  weights:
    sharpness: 0.3
    exposure: -0.15
    aesthetics: 0.25
    saliency: 0.15
    motion: 0.35  # Motion important but not dominant
    
  saliency_prompts:
    - "subject in motion"
    - "tracking shot"
    - "following action"

motion:
  smoothness_weight: 0.4
  stability_weight: 0.4  # Balance smoothness and stability
  consistency_weight: 0.2
  penalize_reversals: true
  reversal_penalty: 0.5
  max_shake_threshold: 2.5  # More tolerant of shake
  optimal_motion_range: [2.0, 8.0]  # Faster motion acceptable

shot_detection:
  enabled: true
  histogram_threshold: 0.35
  edge_threshold: 0.3
  motion_threshold: 12.0
  min_shot_length: 1.5

temporal:
  smooth_window_seconds: 2.0
  min_peak_distance_seconds: 3.0
  motion_aware: true
  static_window_seconds: 3.0
  dynamic_window_seconds: 1.0  # Smaller window for fast action
  motion_threshold: 3.0

clips:
  pre_roll_seconds: 1.0
  post_roll_seconds: 1.0
  video_codec: "libx264"
  crf: 22
  preset: "medium"

diversity:
  enabled: true
  similarity_threshold: 0.8