"""initial schema

Revision ID: 6b8240022727
Revises: 
Create Date: 2025-08-10 06:30:08.107002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b8240022727'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('upload_duration', sa.Float(), nullable=True),
    sa.Column('queue_duration', sa.Float(), nullable=True),
    sa.Column('processing_duration', sa.Float(), nullable=True),
    sa.Column('total_duration', sa.Float(), nullable=True),
    sa.Column('total_video_size_mb', sa.Float(), nullable=True),
    sa.Column('average_video_length_seconds', sa.Float(), nullable=True),
    sa.Column('video_resolution', sa.String(), nullable=True),
    sa.Column('clips_extracted', sa.Integer(), nullable=True),
    sa.Column('best_clip_score', sa.Float(), nullable=True),
    sa.Column('average_clip_score', sa.Float(), nullable=True),
    sa.Column('gpu_seconds_used', sa.Float(), nullable=True),
    sa.Column('memory_peak_mb', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_metrics_job_id'), 'job_metrics', ['job_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('property_type', sa.String(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Float(), nullable=True),
    sa.Column('square_feet', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=False),
    sa.Column('video_s3_urls', sa.JSON(), nullable=False),
    sa.Column('runpod_job_id', sa.String(), nullable=True),
    sa.Column('runpod_status', sa.String(), nullable=True),
    sa.Column('result_s3_urls', sa.JSON(), nullable=True),
    sa.Column('clips_generated', sa.Integer(), nullable=True),
    sa.Column('processing_duration', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('client_ip', sa.String(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_health',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('database_status', sa.String(), nullable=False),
    sa.Column('s3_status', sa.String(), nullable=False),
    sa.Column('runpod_status', sa.String(), nullable=False),
    sa.Column('redis_status', sa.String(), nullable=False),
    sa.Column('pending_jobs', sa.Integer(), nullable=False),
    sa.Column('processing_jobs', sa.Integer(), nullable=False),
    sa.Column('failed_jobs_24h', sa.Integer(), nullable=False),
    sa.Column('average_processing_time', sa.Float(), nullable=True),
    sa.Column('success_rate_24h', sa.Float(), nullable=True),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_health')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_job_metrics_job_id'), table_name='job_metrics')
    op.drop_table('job_metrics')
    # ### end Alembic commands ###
